catch and report missing output file

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -34,6 +34,10 @@ runs:
         cd VisualSoar
         ./gradlew run --args="--check productionsAgainstDatamap --project ${{ inputs.projectPath }}" --json | tee visualsoar_dm_validation_log.jsonl
         gradle_exit_code=${PIPESTATUS[0]}
+        if [ ! -f visualsoar_dm_validation_log.jsonl ]; then
+          echo "Error: visualsoar_dm_validation_log.jsonl was not created."
+          exit 1
+        fi
         exit $gradle_exit_code
 
     - name: Annotate with Validation Results
